config/routes.rb
Rails.application.routes.draw do

  resources :teams
  get 'search/results'

  resources :comments, only: [:index, :new, :create]

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/profile' => 'users#profile'
  post '/users/make_admin/:id' => 'users#make_admin'
  post '/users/demote_admin/:id' => 'users#demote_admin'
  get '/submissions/upvote/:id' => 'submissions#upvote'
  post '/submissions/upvote/:id' => 'submissions#upvote'
  get '/submissions/downvote/:id' => 'submissions#downvote'
  post '/submissions/downvote/:id' => 'submissions#downvote'
  get '/challenges/upvote/:id' => 'challenges#upvote'
  post '/challenges/upvote/:id' => 'challenges#upvote'
  get '/challenges/downvote/:id' => 'challenges#downvote'
  post '/challenges/downvote/:id' => 'challenges#downvote'

  post '/teams/join/:id' => 'teams#join'
  post '/teams/leave/:id' => 'teams#leave'
  post '/teams/:id' => 'teams#show'

  resources :submissions do
    resources :users do
    end
    resources :comments do
    end
  end
  resources :challenges do
    resources :users do
    end
    resources :submissions do
    end
  end
  resources :users do
    resources :challenges do
    end
    resource :submissions do
    end
   end

  root 'welcome#index'

  match ':controller(/:action(/:id))', :via => :get
end

app/models/user.rb
class User < ActiveRecord::Base
  has_merit


	has_many :user_interactions, :dependent => :destroy
	has_many :submissions, :through => :user_interactions, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, :omniauth_providers => [:google_oauth2]

	has_many :us_chal_interactions, :dependent => :destroy
	has_many :challenges, :through => :us_chal_interactions, :dependent => :destroy
	has_many :comments, :dependent => :destroy
  belongs_to :team

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
	validates :email, :presence => true, :format => EMAIL_REGEX, uniqueness: true
  validates :username, :presence => true, uniqueness: true
  validates_length_of :username, :maximum => 20

  after_initialize :set_defaults, unless: :persisted?
  
  mount_uploader :image, ImageUploader

  def self.search(search)
    where("username LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%")
  end

  def set_defaults
   
  end

  def self.google_from_omniauth(access_token)
      data = access_token
      user = User.where(:email => data['info']["email"]).first

      unless user
        user = User.create(
              email: data['info']['email'],
              password: Devise.friendly_token[0,20],
              provider: data['provider'],
              username: data['info']["email"],
              uid: data['uid']
           )
        user.remote_image_url = data['info']['image']
       end

      # skip confirmation email when using oauth
      user.skip_confirmation!

      return user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    if is_admin?
      @users = User.all
    else
      redirect_to '/profile'
    end
    if params[:search]
      @users = User.search(params[:search]).order("userscore DESC")
    else
      @users = User.all.order("userscore DESC")
    end
  end


  def profile
     @user = current_user
     @mysubmissions = []
     @user.submissions.each do |submission|
       if submission.user_interactions.where(:user_id => @user.id).first.interaction == "created"
         @mysubmissions << submission
       end
     end
     @challenges = Challenge.all
     @mychallenges = []
     @user.challenges.each do |challenge|
       if challenge.us_chal_interactions.where(:user_id => @user.id).first.interaction == "created"
         @mychallenges << challenge
       end
     end
  end
  # GET /users/1
  # GET /users/1.json

  def show
    if user_signed_in?
      @user = User.find(params[:id])
    @mysubmissions = []
     @user.submissions.each do |submission|
       if submission.user_interactions.where(:user_id => @user.id).first.interaction == "created"
         @mysubmissions << submission
       end
     end
     @challenges = Challenge.all
     @mychallenges = []
     @user.challenges.each do |challenge|
       if challenge.us_chal_interactions.where(:user_id => @user.id).first.interaction == "created"
         @mychallenges << challenge
       end
     end
    end
  end


  # GET /users/new

  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if user_signed_in?
      @user = User.find(params[:id])
      unless current_user == @user
        flash[:notice] = "You can only edit your own user account!"
        redirect_to users_path(current_user)
        return
      end
    end
  end

  # POST /users
  # POST /users.json
  /
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  /

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if is_admin?
      @user = User.find(params[:id])
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def make_admin
    if is_admin?
      @user = User.find(params[:id])
      @user.admin = true
      @user.save
      @users = User.all
    end
  end

  def demote_admin
    if is_admin?
      @user = User.find(params[:id])
      @user.admin = false
      @user.save
      @users = User.all
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :username, :userscore, :team, :admin, :image, :bio, :birthdate, :location)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container" >
  <div class="form-group row">
    <%= f.label :email, class: "col-xs-2 col-form-label" %>
     <div class="col-xs-10">
    <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :username, class: "col-xs-2 col-form-label" %>
     <div class="col-xs-10">
    <%= f.text_field :username, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :image, class: "col-xs-2 col-form-label" %>
     <div class="col-xs-10">
    <%= f.file_field :image, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :birthdate, class: "col-xs-2 col-form-label" %>
     <div class="col-xs-10">
    <%= f.date_field :birthdate, class: "form-control" %>
    </div>
  </div>
    <div class="form-group row">
    <%= f.label :location, class: "col-xs-2 col-form-label" %>
     <div class="col-xs-10">
    <%= f.text_field :location, class: "form-control" %>
    </div>
  </div>
    <div class="form-group row">
    <%= f.label :bio, class: "col-xs-2 col-form-label" %>
     <div class="col-xs-10">
    <%= f.text_field :bio, class: "form-control" %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-secondary" %>
  </div>
<% end %>
</div>

app/views/users/_users.erb
<% users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.userscore %></td>
        <td><%= user.team_id %></td>
        <td><%= user.admin ? "Yes" : "No" %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to("Destroy", {:action => "destroy", :id => user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :delete, data: {confirm: "Are you sure?"}) %></td>
        <td>
        <% if !user.admin? %> <%= link_to("Make Admin", {:action => "make_admin", :id => user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post) %> <% end %>
        <% if user.admin? %> <%= link_to("Demote Admin", {:action => "demote_admin", :id => user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post) %> <% end %>
        </td>
      </tr>
<% end %>

app/views/users/demote_admin.js.erb
$("#users_table").html("<%= escape_javascript(render partial: 'users', locals: { users: @users } ) %>"); 

app/views/users/edit.html.erb
<!--<%= link_to("<< Back to List", {:action => 'index'}) %>-->
<h1>Edit Profile</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>-->

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Email</th>
      <th>Username</th>
      <th>Points</th>
      <th>Team</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="users_table">
    <%= render partial: 'users', locals: {users: @users}  %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

<%= form_tag(users_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
<%= submit_tag "Search!" %>
<% end %>

app/views/users/make_admin.js.erb
$("#users_table").html("<%= escape_javascript(render partial: 'users', locals: { users: @users } ) %>"); 

app/views/users/new.html.erb
<%#= link_to("Back", {:action => 'index'}) %>

<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/profile.html.erb
<%#= link_to("Back", {:action => 'index'}) %>

<!--<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Points:</strong>
  <%= @user.points %>
</p>

<p>
  <strong>Team:</strong>
  <% if @user.team_id %>
  <%= @user.team_id %>
  <% else %> None <% end %>
</p>

<p>
  <strong>Achievements:</strong>
</p>-->

<!--<h1 class="card-title"><%= @user.username %></h1>-->
<div class="container">
<div class="card-deck-wrapper mt-2">
  <div class="card-deck">
   <div class="card">
    <div class="card-block">
    <div class="col-sm-2">
      <img src="<%= @user.image %>" style="width:100%">
    </div>
     <div class="col-sm-10">
        <div class="card-title"><span class="h1"><%= @user.username %></span>
            <% if @user == current_user %>
            <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
            <% end %>
        </div>
              <p class="card-text">Email: <%= @user.email %></p>
              <p class="card-text">Challenger Points: <%= @user.userscore %></p>
              <p class="card-text">Team: <% if @user.team_id %>
                <%= link_to @user.team.name, @user.team %>
                <% else %> None <% end %></p>
              <% if not @user.badges.blank? %>
              <p class="card-text">Badges:
                <% @user.badges.each do |badge| %>
                  <span data-toggle="tooltip" title="<%= badge.description %>"><%= badge.name %></span> |
                <% end %>
              <% end %>
              <% if not @user.birthdate.blank? %>
              </p>
              <p class="card-text">Birthday: <%= @user.birthdate %></p>
              <% end %>
              <% if not @user.location.blank? %>
              <p class="card-text">Location: <%= @user.location %></p>
              <% end %>
              <% if not @user.bio.blank? %>              
              <p class="card-text">Bio: <%= @user.bio %></p>
              <!--<p class="card-text">Achievements:</p>-->
              <% end %>
            </div>
          </div>
        </div>
      </div>
  </div>
<% if not @mysubmissions.blank? %>
<h2>My Submissions</h2>
<hr>
<%= render partial: "submissions/cards", locals: {submissions: @mysubmissions} %>
<% end %>

<% if not @mychallenges.blank? %>
<h2>My Challenges</h2>
<hr>
<%= render partial: "challenges/cards", locals: {challenges: @mychallenges} %>
<% end %>

</div>
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>

app/views/users/show.html.erb
<%#= link_to("Back", {:action => 'index'}) %>

<div class="container">
<div class="card-deck-wrapper mt-2">
  <div class="card-deck">
   <div class="card">
    <div class="card-block">
    <div class="col-sm-2">
      <img src="<%= @user.image %>" style="width:100%">
    </div>
     <div class="col-sm-10">
        <div class="card-title"><span class="h1"><%= @user.username %></span>
            <% if @user == current_user %>
            <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
            <% end %>
        </div>
              <p class="card-text">Email: <%= @user.email %></p>
              <p class="card-text">Challenger Points: <%= @user.userscore %></p>
              <p class="card-text">Team: <% if @user.team_id %>
                <%= link_to @user.team.name, @user.team %>
                <% else %> None <% end %></p>
              <% if not @user.badges.blank? %>
              <p class="card-text">Badges:
                <% @user.badges.each do |badge| %>
                  <span data-toggle="tooltip" title="<%= badge.description %>"><%= badge.name %></span> |
                <% end %>
              <% end %>
              </p>
              <% if not @user.birthdate.blank? %>
              </p>
              <p class="card-text">Birthday: <%= @user.birthdate %></p>
              <% end %>
              <% if not @user.location.blank? %>
              <p class="card-text">Location: <%= @user.location %></p>
              <% end %>
              <% if not @user.bio.blank? %>              
              <p class="card-text">Bio: <%= @user.bio %></p>
              <!--<p class="card-text">Achievements:</p>-->
              <% end %>
            </div>
          </div>
        </div>
      </div>
  </div>

<br>
<% if not @mysubmissions %>
<h2><%= @user.username %> Submissions</h2>
<hr>
<%= render partial: "submissions/cards", locals: {submissions: @mysubmissions} %>
<% end %>

<% if not @mychallenges.blank? %>
<h2><%= @user.username %> Challenges</h2>
<hr>
<%= render partial: "challenges/cards", locals: {challenges: @mychallenges} %>
<% end %>
<!--<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Points:</strong>
  <%= @user.points %>
</p>

<p>
  <strong>Team:</strong>
  <%= @user.team_id %>
</p>

<% if @user == current_user %>
    <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-secondary' %>
<% end%>
<% if not @mysubmissions.blank? %>
<hr>
<h4 class="card-title">Submissions:</h4>
<div class="card-deck-wrapper mt-2">
  <div class="card-deck">
  <% if @mysubmissions.each do |submission| %>
      <div class="card submission" data-url="<%= challenge_submission_path(@challenges.find(submission.challenge_id).id, submission)%>">
          <div class="card-block">
            <small class="h6"><p class="floatright"><%= link_to 'Edit', edit_challenge_submission_path(@challenges.find(submission.challenge_id).id, submission.id) %></p></small>
            <h3 class="card-title"><%= @challenges.find(submission.challenge_id).name %> Challenge </h3>
            <p class="card-text"><a href="<%= submission.url %>"> <%=submission.url %></a></p>
            <p class="card-text">Score: <%= submission.score %></p>
            <p class="card-text"><small class="text-muted"></small></p>
          </div>
        </a>
      </div>
    <% end %>
    <% end %>
  </div>
</div>
<% end %>

<% if not @mychallenges.blank? %>
<hr>
<h5> Challenges proposed by <%= @user.username %>: </h5>
<div class="card-deck-wrapper mt-2">
  <div class="card-deck">
  <% @topchallenges = @mychallenges.sort_by { |chall| chall.score} %>
  <% @topchallenges.each do |challenge| %>
      <div class="card challenge" data-url="<%= challenge_path(challenge)%>">
          <div class="card-block">
            <div class="card-title"><span class="h2"><%= challenge.name %></span>
              <span class="h6 ml-1">By: <%= challenge.us_chal_interactions.where(:interaction => "created").first.user.username %></span>
              <span class="h6 ml-1">Total score: <%= challenge.score%></span>
            </div>
              <p class="card-text"><i><%= challenge.description %></i></p><br>
              <hr>
            <% @subs = challenge.submissions.sort_by { |sub| sub.score} %>
            <% if not @subs.blank? %>
              <% @topsub = @subs[0] %>
                Top Submission: <%= @topsub.user_interactions.where(:interaction => "created").first.user.username %>
                Score: <%= @topsub.score %>
            <% else %>
              <p class="lead"> There are no submissions to this challenge yet! </p>
            <% end %>
          </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>
</div>
<% end %>-->
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>