config/routes.rb
Rails.application.routes.draw do

  resources :teams
  get 'search/results'

  resources :comments, only: [:index, :new, :create]

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/profile' => 'users#profile'
  post '/users/make_admin/:id' => 'users#make_admin'
  post '/users/demote_admin/:id' => 'users#demote_admin'
  get '/submissions/upvote/:id' => 'submissions#upvote'
  post '/submissions/upvote/:id' => 'submissions#upvote'
  get '/submissions/downvote/:id' => 'submissions#downvote'
  post '/submissions/downvote/:id' => 'submissions#downvote'
  get '/challenges/upvote/:id' => 'challenges#upvote'
  post '/challenges/upvote/:id' => 'challenges#upvote'
  get '/challenges/downvote/:id' => 'challenges#downvote'
  post '/challenges/downvote/:id' => 'challenges#downvote'

  post '/teams/join/:id' => 'teams#join'
  post '/teams/leave/:id' => 'teams#leave'
  post '/teams/:id' => 'teams#show'

  resources :submissions do
    resources :users do
    end
    resources :comments do
    end
  end
  resources :challenges do
    resources :users do
    end
    resources :submissions do
    end
  end
  resources :users do
    resources :challenges do
    end
    resource :submissions do
    end
   end

  root 'welcome#index'

  match ':controller(/:action(/:id))', :via => :get
end

app/models/submission.rb
class Submission < ActiveRecord::Base
	has_many :user_interactions, :dependent => :destroy
	has_many :users, :through => :user_interactions
	has_many :comments
	belongs_to :challenge
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  before_action :authenticate_user!

  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
    @users = User.all
    @challenges = Challenge.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @submission = Submission.find(params[:id])
    @user = User.find(current_user.id)
    @interaction = UserInteraction.where(:user_id => current_user.id, :submission_id => @submission.id).first
    @challenge = Challenge.find(@submission.challenge_id)
    @comments = @submission.comments
    @users = User.all
  end

  # GET /challenges/:challenge_id/submissions/new
  def new
    @challenge = Challenge.find(params[:challenge_id]);
    @submission = Submission.new
    @user = current_user
  end

  # GET /submissions/1/edit
  def edit
    @user = @submission.user_interactions.where(:interaction => "created").first.user
  end

  # POST /challenges/:challenge_id/submissions
  # POST /challenges/:challenge_id/submissions.json
  def create
    @submission = Submission.new(submission_params)
    @user = User.find(current_user.id)
    @interaction = UserInteraction.create(:interaction => "created")
    @user.user_interactions << @interaction
    @submission.user_interactions << @interaction

    if params[:submission][:filedata]
      @upload_url = "https://api.vid.me/video/upload"

      # Call vidme API to upload video
      @payload = {
              :multipart => true,
              :filedata => params[:submission][:filedata],
              :title => @submission.name,
              :description => @submission.description
            }

      request = RestClient::Request.new({
            :method => 'post',
            :url => @upload_url,
            :payload => @payload
      })

      # Catch Errors
      begin
        response = request.execute
      rescue RestClient::ExceptionWithResponse => e
        response = JSON.parse(e.response)
        flash[:alert] = response['error']
        redirect_to(:back) and return
      end

      # Update submission with data
      response = JSON.parse(response)
      @video_id =  response['video']['video_id']
      @submission.url = response['video']['full_url']
      @submission.embed = response['video']['embed_url']
      @submission.duration = response['video']['duration']

      # Get Thumbnail for video
      @get_url = 'https://api.vid.me/video/' + @video_id
      response = RestClient.get(@get_url)
      response = JSON.parse(response)
      @submission.thumbnail = response['video']['thumbnail_url']
    end

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end

    # Add User Interaction # Matt I moved this after save because it was failing

    @user = current_user

    @challenge = Challenge.find(params[:challenge_id])
    @challenge.submissions << @submission
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    @submission = Submission.find(params[:id])
    @user = User.find(params[:user])
    @cre_user = @submission.user_interactions.where(:interaction => 'created').first.user
    if params[:st] == 'none'
      @interaction = UserInteraction.create(:interaction => 'liked')
      @user.user_interactions << @interaction
      @submission.user_interactions << @interaction
      @submission.update_attributes(:score => @submission.score + 1)
      @cre_user.update_attributes(:userscore => @cre_user.userscore + 1)
    else
      @interaction = @submission.user_interactions.where(:user_id => @user.id).first
      if params[:st] == 'neither'
        @interaction.update_attributes(:interaction => 'liked')
        @submission.update_attributes(:score => @submission.score + 1)
        @cre_user.update_attributes(:userscore => @cre_user.userscore + 1)
      elsif params[:st] == 'like'
        @interaction.update_attributes(:interaction => 'neutral')
        @submission.update_attributes(:score => @submission.score - 1)
        @cre_user.update_attributes(:userscore => @cre_user.userscore - 1)
      else
        @interaction.update_attributes(:interaction => 'liked')
        @submission.update_attributes(:score => @submission.score + 2)
        @cre_user.update_attributes(:userscore => @cre_user.userscore + 2)
      end
    end
    redirect_to(:action => 'show')
  end

  def downvote
    @submission = Submission.find(params[:id])
    @user = User.find(params[:user])
    @cre_user = @submission.user_interactions.where(:interaction => 'created').first.user
    if params[:st] == 'none'
      @interaction = UserInteraction.create(:interaction => 'disliked')
      @user.user_interactions << @interaction
      @submission.user_interactions << @interaction
      @submission.update_attributes(:score => @submission.score - 1)
      @cre_user.update_attributes(:userscore => @cre_user.userscore - 1)
    else
      @interaction = @submission.user_interactions.where(:user_id => @user.id).first
      if params[:st] == 'neither'
        @interaction.update_attributes(:interaction => 'disliked')
        @submission.update_attributes(:score => @submission.score - 1)
        @cre_user.update_attributes(:userscore => @cre_user.userscore - 1)
      elsif params[:st] == 'like'
        @interaction.update_attributes(:interaction => 'disliked')
        @submission.update_attributes(:score => @submission.score - 2)
        @cre_user.update_attributes(:userscore => @cre_user.userscore - 2)
      else
        @interaction.update_attributes(:interaction => 'neutral')
        @submission.update_attributes(:score => @submission.score + 1)
        @cre_user.update_attributes(:userscore => @cre_user.userscore + 1)
      end
    end
    redirect_to(:action => 'show')
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:score, :challenge_id, :url, :description, :name, :embed, :thumbnail, :duration)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_cards.html.erb
<div class="card-columns mt-2">
  <div class="card-deck-wrapper">
    <div class="card-deck">
    <% submissions.sort_by { |submission| submission.score}.reverse!.each do |submission| %>
        <div class="card submission mb-1" data-url="<%= challenge_submission_path(submission.challenge, submission)%>">
            <div class="card-block">
              <div class="card-title">
                <h4><%= submission.challenge.name %></h4>
                <h6>By: <%= submission.user_interactions.where(:interaction => "created").first.user.username %></h6>
              </div>
              <% if submission.thumbnail? %>
                <img height="100px" src="<%= submission.thumbnail %>" alt="Card image">
              <% end %>
              <p class="card-text">Score: <%= submission.score %></p>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script>
  $('.submission').click(function(){
    window.location.href = $(this).data('url');
  });
  $('.submission a').click(function(e){
    e.stopPropagation();
  });
</script>

app/views/submissions/_form.html.erb
<%= form_for([@challenge, @submission]) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong>Submission to challenge from:</strong> <%= @user.username %>
  </div>

 <!-- TODO: Temporary until handeld in backend -->
  <div class="form-group">
    <%= f.file_field :filedata %>
  </div>
  <div class="form-group">
    <%= f.label "Title" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label "Description" %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
   
  <%= f.submit class: "btn btn-secondary" %>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<h1>Listing Submissions</h1>

<%= render partial: "cards", locals: {submissions: @submissions} %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form' %>

<%= link_to 'Back', challenge_path(@challenge) %>

app/views/submissions/show.html.erb
<div class="container">
<h1>
  <%= @submission.name %>
</h1>

<% if @submission.embed %>
  <iframe src="<%= @submission.embed %>" width="100%" height="500" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen scrolling="no"></iframe>
<% end%>

<div class="card-deck-wrapper mt-2">
  <div class="card-deck">
      <div class="card" data-url="<%= challenge_submission_path(@challenge, @submission)%>">
          <div class="card-block">
            <h5 class="card-title">Submission to: <small class="h6">
            <% if (@submission.user_interactions.where(:interaction => "created").first.user == current_user) %>
              <p class="floatright"><%= link_to 'Edit', edit_challenge_submission_path(@challenge.id, @submission.id) %></p>
            <% end%>
            </small></h5>
            <h3 class="card-title"><%= Challenge.find(@submission.challenge_id).name %> Challenge </h3>
            <p class="card-text">By: <%= @submission.user_interactions.where(:interaction => "created").first.user.username %></p>
            <p class="card-text"><a href="<%= @submission.url %>"> <%=@submission.url %></a></p>
            <h3 class="card-text">Score: <%= @submission.score %></h3>
            <p class="card-text">
              <% if !@interaction || @interaction.interaction != "created" %>
                <% if !@interaction %>
                  <%= link_to("+1", {:action => 'upvote', :id => @submission.id, :st => 'none', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-primary') %> /
                  <%= link_to("-1", {:action => 'downvote', :id => @submission.id, :st => 'none', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-danger') %>
                <% else %>
                  <% case @interaction.interaction %>
                  <% when "neutral" %>
                    <%= link_to("+1", {:action => 'upvote', :id => @submission.id, :st => 'neither', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-primary') %> /
                    <%= link_to("-1", {:action => 'downvote', :id => @submission.id, :st => 'neither', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-danger') %>
                  <% when "liked" %>
                    <%= link_to("cancel", {:action => 'upvote', :id => @submission.id, :st => 'like', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-default') %> /
                    <%= link_to("-1", {:action => 'downvote', :id => @submission.id, :st => 'like', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-danger') %>
                  <% else %>
                    <%= link_to("+1", {:action => 'upvote', :id => @submission.id, :st => 'dislike', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-primary') %> /
                    <%= link_to("-cancel", {:action => 'downvote', :id => @submission.id, :st => 'dislike', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-standard') %>
                  <% end %>
                <% end %>
              <% end %>
            </p>
            <p class="card-text"><small class="text-muted"><!-- TODO: submission uploaded --></small></p>
          <% if (@submission.user_interactions.where(:interaction => "created").first.user == current_user) %>
          <%= button_to 'Destroy', @submission, method: :delete, data: { confirm: 'Are you sure?' }, form_class: "inline ", class: "btn btn-danger" %>
          <% end%>
          </div>
      </div>
  </div>
</div>
<h4> Comments </h4>
<% @comments.each do |comment|  %>
<hr>
<p> <strong> <%= @users.find(comment.user_id).username %> | <%= comment.created_at.to_formatted_s(:short) %> </strong> </p>
<p> <%= comment.bodytext %> </p>
<% end %>
<h6> Add a comment!: </h6>
  <%= render "comments/form" %>
  
</div>