config/routes.rb
Rails.application.routes.draw do

  resources :teams
  get 'search/results'

  resources :comments, only: [:index, :new, :create]

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/profile' => 'users#profile'
  post '/users/make_admin/:id' => 'users#make_admin'
  post '/users/demote_admin/:id' => 'users#demote_admin'
  get '/submissions/upvote/:id' => 'submissions#upvote'
  post '/submissions/upvote/:id' => 'submissions#upvote'
  get '/submissions/downvote/:id' => 'submissions#downvote'
  post '/submissions/downvote/:id' => 'submissions#downvote'
  get '/challenges/upvote/:id' => 'challenges#upvote'
  post '/challenges/upvote/:id' => 'challenges#upvote'
  get '/challenges/downvote/:id' => 'challenges#downvote'
  post '/challenges/downvote/:id' => 'challenges#downvote'

  post '/teams/join/:id' => 'teams#join'
  post '/teams/leave/:id' => 'teams#leave'
  post '/teams/:id' => 'teams#show'

  resources :submissions do
    resources :users do
    end
    resources :comments do
    end
  end
  resources :challenges do
    resources :users do
    end
    resources :submissions do
    end
  end
  resources :users do
    resources :challenges do
    end
    resource :submissions do
    end
   end

  root 'welcome#index'

  match ':controller(/:action(/:id))', :via => :get
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	has_many :us_chal_interactions, :dependent => :destroy
	has_many :users, :through => :us_chal_interactions
	has_many :submissions, :dependent => :destroy # if a challenge is deleted, all submissions under that challenge should be deleted also
	validates_length_of :name, :maximum => 50
	validates_length_of :description, :maximum => 500
end

def Challenge.search(search)
	where("name LIKE ?", "%#{search}%")
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
    @users = User.all
    if params[:search]
      @challenges = Challenge.search(params[:search]).order("score DESC")
    else
      @challenges = Challenge.all.order("created_at DESC")
    end
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
    @challenge = Challenge.find(params[:id])
    @users = User.all
    @user = User.find(current_user.id)
    @cre_user = @challenge.us_chal_interactions.where(:interaction => "created").first.user
    @interaction = UsChalInteraction.where(:user_id => current_user.id, :challenge_id => @challenge.id).first
    @submissions = @challenge.submissions
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
    @user = current_user
  end

  # GET /challenges/1/edit
  def edit
    @user = @challenge.us_chal_interactions.where(:interaction => "created").first.user
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)
    @user = User.find(current_user.id)
    @interaction = UsChalInteraction.create(:interaction => "created")
    @user.us_chal_interactions << @interaction
    @challenge.us_chal_interactions << @interaction

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
    # @user = @challenge.us_chal_interactions.where(:interaction => "created").first.user  # Matt - what is this for?
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @challenge = Challenge.find(params[:id])
    @user = User.find(params[:user])
    @cre_user = @challenge.us_chal_interactions.where(:interaction => "created").first.user
    if params[:st] == 'none'
      @interaction = UsChalInteraction.create(:interaction => 'liked')
      @user.us_chal_interactions << @interaction
      @challenge.us_chal_interactions << @interaction
      @challenge.update_attributes(:score => @challenge.score + 1)
      @cre_user.update_attributes(:userscore => @cre_user.userscore + 1)
    else
      @interaction = @challenge.us_chal_interactions.where(:user_id => @user.id).first
      if params[:st] == 'neither'
        @interaction.update_attributes(:interaction => 'liked')
        @challenge.update_attributes(:score => @challenge.score + 1)
        @cre_user.update_attributes(:userscore => @cre_user.userscore + 1)
      elsif params[:st] == 'like'
        @interaction.update_attributes(:interaction => 'neutral')
        @challenge.update_attributes(:score => @challenge.score - 1)
        @cre_user.update_attributes(:userscore => @cre_user.userscore - 1)
      else
        @interaction.update_attributes(:interaction => 'liked')
        @challenge.update_attributes(:score => @challenge.score + 2)
        @cre_user.update_attributes(:userscore => @cre_user.userscore + 2)
      end
    end
    redirect_to(:action => 'show')
  end

  def downvote
    @challenge = Challenge.find(params[:id])
    @user = User.find(params[:user])
    @cre_user = @challenge.us_chal_interactions.where(:interaction => "created").first.user
    if params[:st] == 'none'
      @interaction = UsChalInteraction.create(:interaction => 'disliked')
      @user.us_chal_interactions << @interaction
      @challenge.us_chal_interactions << @interaction
      @challenge.update_attributes(:score => @challenge.score - 1)
      @cre_user.update_attributes(:userscore => @cre_user.userscore - 1)
    else
      @interaction = @challenge.us_chal_interactions.where(:user_id => @user.id).first
      if params[:st] == 'neither'
        @interaction.update_attributes(:interaction => 'disliked')
        @challenge.update_attributes(:score => @challenge.score - 1)
        @cre_user.update_attributes(:userscore => @cre_user.userscore - 1)
      elsif params[:st] == 'like'
        @interaction.update_attributes(:interaction => 'disliked')
        @challenge.update_attributes(:score => @challenge.score - 2)
        @cre_user.update_attributes(:userscore => @cre_user.userscore - 2)
      else
        @interaction.update_attributes(:interaction => 'neutral')
        @challenge.update_attributes(:score => @challenge.score + 1)
        @cre_user.update_attributes(:userscore => @cre_user.userscore + 1)
      end
    end
    redirect_to(:action => 'show')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:name, :score, :description)
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_cards.html.erb
<div class="card-columns mt-2">
  <div class="card-deck-wrapper">
    <div class="card-deck">
      <% challenges.reverse.each do |challenge| %>
        <div class="card challenge mb-1" data-url="<%= challenge_path(challenge)%>">
          <div class="card-block">
            <div class="card-title">
              <span class="h2"><%= challenge.name %></span>
            </div>
            <span class="h6 ml-1">By: <%= challenge.us_chal_interactions.where(:interaction => "created").first.user.username %></span>
            <span class="h6 ml-1">Total score: <%= challenge.score%></span>
            <p class="card-text"><i><%= challenge.description %></i></p><br>
            <hr>
            <% @subs = challenge.submissions.sort_by { |sub| sub.score} %>
            <% if not @subs.blank? %>
              <% @subs = @subs.reverse %>
              <% @topsub = @subs[0] %>
                Top Submission: <%= @topsub.user_interactions.where(:interaction => "created").first.user.username %>
                Score: <%= @topsub.score %>
            <% else %>
              <p class="lead"> There are no submissions to this challenge yet! </p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $('.challenge').click(function(){
    window.location.href = $(this).data('url');
  });
   $(".challenge a").click(function(e) {
   //prevent going to view when click on link inside card
   e.stopPropagation();
  });
</script>

app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
  <% if @challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% @challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <strong>Submitting Challenge from:</strong> <%= @user.username %>
  </div>
  <div class="form-group">
    Challenge Title<br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
   <div class="form-group">
    Challenge Description<br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="actions">

    <%= link_to 'Back', challenges_path, :class=>"btn btn-secondary" %>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<div class="container">
    <h1>Editing Challenge</h1>

    <%= render 'form' %>
</div>

app/views/challenges/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div>
      <span class="h1">All Challenges <%= link_to 'Create Challenge', new_challenge_path, class: "btn btn-primary" %></span>
      <span class="float-xs-right">
            <%= form_tag(challenges_path, :method => "get", id: "search-form", class: "form-inline") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Challenges", class: "form-control" %>
            <%= submit_tag "Search!", class: "btn btn-secondary" %>
            <% end %>
      </span>
    </div>
  </div>
</div>

<% @topchallenges = @challenges.sort_by { |chall| chall.score} %>
<%= render partial: "cards", locals: {challenges: @topchallenges} %>

app/views/challenges/new.html.erb
<div class="container">
    <h1>New Challenge</h1>

    <%= render 'form' %>
    
</div>

app/views/challenges/show.html.erb
<div class="mb-1">
    <span class="h1">
      <%= @challenge.name %>
    </span>
    <span class="text-muted h6">Created by <%= link_to @cre_user.username, @cre_user %></span>
    <% if @challenge.us_chal_interactions.where(:interaction => "created").first.user == current_user %>
    <span class="h6"><%= link_to 'Edit', edit_challenge_path(@challenge), class: "btn btn-secondary" %></span>
      <%= button_to 'Destroy', @challenge, method: :delete, data: { confirm: 'Are you sure?' }, form_class: "inline ", class: "btn btn-danger" %>
    <% end %>
</div>

<p>Score: <%= @challenge.score %></p>

<p class="card-text">
  <% if !@interaction || @interaction.interaction != "created" %>
    <% if !@interaction %>
      <%= link_to("+1", {:action => 'upvote', :id => @challenge.id, :st => 'none', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-success') %>
      <%= link_to("-1", {:action => 'downvote', :id => @challenge.id, :st => 'none', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-danger') %>
    <% else %>
      <% case @interaction.interaction %>
      <% when "neutral" %>
        <%= link_to("+1", {:action => 'upvote', :id => @challenge.id, :st => 'neither', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-success') %> /
        <%= link_to("-1", {:action => 'downvote', :id => @challenge.id, :st => 'neither', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-danger') %>
      <% when "liked" %>
        <%= link_to("cancel", {:action => 'upvote', :id => @challenge.id, :st => 'like', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-secondary') %> /
        <%= link_to("-1", {:action => 'downvote', :id => @challenge.id, :st => 'like', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-danger') %>
      <% else %>
        <%= link_to("+1", {:action => 'upvote', :id => @challenge.id, :st => 'dislike', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-sucess') %> /
        <%= link_to("-cancel", {:action => 'downvote', :id => @challenge.id, :st => 'dislike', :user => @user.id, :authenticity_token => form_authenticity_token()}, remote: true, method: :post, class: 'btn btn-danger') %>
      <% end %>
    <% end %>
  <% end %>
</p>

<%= link_to 'New Submission', new_challenge_submission_path(@challenge), class: "btn btn-primary" %>

<%= render partial: "submissions/cards", locals: {submissions: @submissions} %>

<%# link_to("+1", :action => 'upvote', :id => @challenge.id) %>