config/routes.rb
Rails.application.routes.draw do

  resources :teams
  get 'search/results'

  resources :comments, only: [:index, :new, :create]

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", registrations: 'registrations' }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/profile' => 'users#profile'
  post '/users/make_admin/:id' => 'users#make_admin'
  post '/users/demote_admin/:id' => 'users#demote_admin'
  get '/submissions/upvote/:id' => 'submissions#upvote'
  post '/submissions/upvote/:id' => 'submissions#upvote'
  get '/submissions/downvote/:id' => 'submissions#downvote'
  post '/submissions/downvote/:id' => 'submissions#downvote'
  get '/challenges/upvote/:id' => 'challenges#upvote'
  post '/challenges/upvote/:id' => 'challenges#upvote'
  get '/challenges/downvote/:id' => 'challenges#downvote'
  post '/challenges/downvote/:id' => 'challenges#downvote'

  post '/teams/join/:id' => 'teams#join'
  post '/teams/leave/:id' => 'teams#leave'
  post '/teams/:id' => 'teams#show'

  resources :submissions do
    resources :users do
    end
    resources :comments do
    end
  end
  resources :challenges do
    resources :users do
    end
    resources :submissions do
    end
  end
  resources :users do
    resources :challenges do
    end
    resource :submissions do
    end
   end

  root 'welcome#index'

  match ':controller(/:action(/:id))', :via => :get
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Down To Anything</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
  <%= javascript_include_tag "application" %>
  <meta name="google-signin-client_id" content="881367045605-3rp1s8s756hseuitp3fq032b6dfsp0tb.apps.googleusercontent.com">
</head>
<body>
<div class="container-fluid pr-0 pl-0">
  <nav class="navbar navbar-dark bg-inverse topnav">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag("logolong.png", size: "230x30") %></a>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Challenges", challenges_path, :class => 'nav-link' %>
          </li>
           <li class="nav-item">
            <%= link_to "Submissions", submissions_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Teams", teams_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item dropdown float-xs-right">
            <a class="nav-link dropdown-toggle pt-0 pb-0" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img src="<%= current_user.image %>" style="height:45px">
              <%=current_user.username%>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/profile">Profile</a>
              <%= link_to 'Account', edit_user_registration_path, :class => 'dropdown-item' %>
              <%= link_to "Logout", destroy_user_session_path, :class => 'dropdown-item'  %>
            </div>
          </li>
          <% if is_admin? %>
           <li class="nav-item">
            <%= link_to "Users", users_path, :class => 'nav-link' %>
          </li>
          <% end %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
          </li>
        <% end %>
      </ul>
      <form class="form-inline float-xs-left ml-2" method="GET" action="/search/results">
        <input class="form-control" type="text" name="search" id="searchform" placeholder="Search">
        <button class="btn btn-outline-info" type="submit" id="searchbutton">Search</button>
      </form>
    </nav>
    </div>
  </div>

<div class="container-fluid">
<div class="container">
  <% if notice %>
    <div class="alert alert-info mt-1 alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger mt-1 alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      <%= alert %>
    </div>
  <% end %>
</div>
  <div class="row">
    <div class="col-xs-12 mt-2">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>